import { randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import { codeHash, generatedCode, normalizeCode, publicCampaign, type CreatePromotionInput, type PromotionAuditEntry, type PromotionCampaign, type PromotionCampaignView, type PromotionRepository } from './PromotionRepository.js';

export class PostgresPromotionRepository implements PromotionRepository {
  constructor(private readonly pool: Pool) {}
  create(input: CreatePromotionInput, actor: string, now: number): Promise<{ campaign: PromotionCampaignView; code: string }> { return transaction(this.pool, async (client) => {
    const code = normalizeCode(input.customCode || generatedCode()); const campaign: PromotionCampaign = { id: randomUUID(), name: input.name, codeHash: codeHash(code), codeHint: `${code.slice(0, 6)}…${code.slice(-4)}`, kind: input.kind, usesPerPlayer: input.usesPerPlayer, discountBps: input.kind === 'mint-discount' ? input.discountBps : undefined, reason: input.reason, maxRedemptions: input.maxRedemptions, startsAt: input.startsAt ?? now, expiresAt: input.expiresAt, status: 'active', redemptions: [], createdBy: actor, createdAt: now, updatedAt: now };
    try { await client.query(`insert into promotion_campaigns(id,name,code_hash,code_hint,kind,uses_per_player,discount_bps,reason,max_redemptions,starts_at,expires_at,status,created_by,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`, campaignValues(campaign)); }
    catch (error) { if ((error as { code?: string }).code === '23505') throw new Error('Promotion code already exists', { cause: error }); throw error; }
    await audit(client, { id: randomUUID(), action: 'promotion.create', actor, campaignId: campaign.id, at: now, detail: `${campaign.kind} · cap ${campaign.maxRedemptions}` }); return { campaign: publicCampaign(campaign, now), code };
  }); }
  async list(now: number): Promise<PromotionCampaignView[]> { return (await campaigns(this.pool, '', [], 'order by c.created_at desc')).map((campaign) => publicCampaign(campaign, now)); }
  async findByCode(code: string): Promise<PromotionCampaign | null> { const values = await campaigns(this.pool, 'where c.code_hash=$1', [codeHash(code)]); return values[0] ?? null; }
  recordRedemption(campaignId: string, sessionId: string, now: number): Promise<PromotionCampaignView> { return transaction(this.pool, async (client) => {
    const value = await lockedCampaign(client, campaignId); const existing = value.redemptions.find((redemption) => redemption.sessionId === sessionId); if (existing) return publicCampaign(value, now);
    if (value.status !== 'active' || value.startsAt > now || value.expiresAt <= now || value.redemptions.length >= value.maxRedemptions) throw new Error('Promotion is unavailable');
    await client.query('insert into promotion_redemptions(campaign_id,session_id,redeemed_at) values($1,$2,$3) on conflict do nothing', [campaignId, sessionId, new Date(now)]);
    value.redemptions.push({ sessionId, at: now }); value.updatedAt = now; await client.query('update promotion_campaigns set updated_at=$2 where id=$1', [campaignId, new Date(now)]); await audit(client, { id: randomUUID(), action: 'promotion.redeem', actor: `player:${sessionId}`, campaignId, at: now, detail: value.kind }); return publicCampaign(value, now);
  }); }
  setPaused(campaignId: string, paused: boolean, actor: string, now: number): Promise<PromotionCampaignView> { return transaction(this.pool, async (client) => {
    const value = await lockedCampaign(client, campaignId); value.status = paused ? 'paused' : 'active'; value.updatedAt = now; await client.query('update promotion_campaigns set status=$2,updated_at=$3 where id=$1', [campaignId, value.status, new Date(now)]); await audit(client, { id: randomUUID(), action: paused ? 'promotion.pause' : 'promotion.resume', actor, campaignId, at: now, detail: value.name }); return publicCampaign(value, now);
  }); }
  async audit(limit = 100): Promise<PromotionAuditEntry[]> { const result = await this.pool.query('select * from promotion_audit order by at desc limit $1', [Math.max(1, Math.min(500, limit))]); return result.rows.map(auditRow); }
}

async function campaigns(queryable: Pool | PoolClient, where = '', parameters: unknown[] = [], order = ''): Promise<PromotionCampaign[]> { const result = await queryable.query(`select c.*,coalesce(json_agg(json_build_object('sessionId',r.session_id,'at',(extract(epoch from r.redeemed_at)*1000)::bigint) order by r.redeemed_at) filter(where r.session_id is not null),'[]') redemptions from promotion_campaigns c left join promotion_redemptions r on r.campaign_id=c.id ${where} group by c.id ${order}`, parameters); return result.rows.map(campaignRow); }
async function lockedCampaign(client: PoolClient, id: string): Promise<PromotionCampaign> { await client.query('select id from promotion_campaigns where id=$1 for update', [id]); const values = await campaigns(client, 'where c.id=$1', [id]); if (!values[0]) throw new Error('Promotion not found'); return values[0]; }
function campaignValues(value: PromotionCampaign): unknown[] { return [value.id, value.name, value.codeHash, value.codeHint, value.kind, value.usesPerPlayer, value.discountBps ?? null, value.reason, value.maxRedemptions, new Date(value.startsAt), new Date(value.expiresAt), value.status, value.createdBy, new Date(value.createdAt), new Date(value.updatedAt)]; }
function campaignRow(row: Record<string, unknown>): PromotionCampaign { return { id: String(row.id), name: String(row.name), codeHash: String(row.code_hash), codeHint: String(row.code_hint), kind: row.kind as PromotionCampaign['kind'], usesPerPlayer: Number(row.uses_per_player), discountBps: row.discount_bps === null ? undefined : Number(row.discount_bps), reason: String(row.reason), maxRedemptions: Number(row.max_redemptions), startsAt: time(row.starts_at), expiresAt: time(row.expires_at), status: row.status as PromotionCampaign['status'], redemptions: (row.redemptions as Array<{ sessionId: string; at: string | number }>).map((item) => ({ sessionId: item.sessionId, at: Number(item.at) })), createdBy: String(row.created_by), createdAt: time(row.created_at), updatedAt: time(row.updated_at) }; }
async function audit(client: PoolClient, value: PromotionAuditEntry): Promise<void> { await client.query('insert into promotion_audit(id,action,actor,campaign_id,at,detail) values($1,$2,$3,$4,$5,$6)', [value.id, value.action, value.actor, value.campaignId, new Date(value.at), value.detail]); }
function auditRow(row: Record<string, unknown>): PromotionAuditEntry { return { id: String(row.id), action: row.action as PromotionAuditEntry['action'], actor: String(row.actor), campaignId: String(row.campaign_id), at: time(row.at), detail: String(row.detail) }; }
function time(value: unknown): number { return new Date(value as string | number | Date).getTime(); }
async function transaction<T>(pool: Pool, operation: (client: PoolClient) => Promise<T>): Promise<T> { const client = await pool.connect(); try { await client.query('begin'); const result = await operation(client); await client.query('commit'); return result; } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
