import { Pool, type PoolClient } from 'pg';
import { playerNameKey, type AccountChallenge, type AccountRepository, type PlayerAccount, type PlayerDeviceSession, type PlayerPasskey } from './AccountRepository.js';

export class PostgresAccountRepository implements AccountRepository {
  constructor(private readonly pool: Pool) {}
  static async connect(connectionString: string): Promise<PostgresAccountRepository> {
    const pool = new Pool({ connectionString, max: Number(process.env.DATABASE_POOL_MAX ?? 10), idleTimeoutMillis: 30_000, connectionTimeoutMillis: 5_000, application_name: 'sketch-arena' });
    await pool.query('select 1'); return new PostgresAccountRepository(pool);
  }
  async findAccount(id: string): Promise<PlayerAccount | null> { const result = await this.pool.query('select * from player_accounts where id=$1', [id]); return result.rows[0] ? account(result.rows[0]) : null; }
  async findByNameKey(nameKey: string): Promise<PlayerAccount | null> { const result = await this.pool.query('select * from player_accounts where name_key=$1', [nameKey]); return result.rows[0] ? account(result.rows[0]) : null; }
  async findByLegacyCredentialHash(hash: string): Promise<PlayerAccount | null> { const result = await this.pool.query('select * from player_accounts where legacy_credential_hash=$1', [hash]); return result.rows[0] ? account(result.rows[0]) : null; }
  async findByPasskeyId(id: string): Promise<{ account: PlayerAccount; passkey: PlayerPasskey } | null> {
    const result = await this.pool.query('select a.*, p.id passkey_id, p.account_id passkey_account_id, p.webauthn_user_id, p.public_key, p.counter, p.device_type, p.backed_up, p.transports, p.label passkey_label, p.created_at passkey_created_at, p.last_used_at from player_passkeys p join player_accounts a on a.id=p.account_id where p.id=$1', [id]);
    return result.rows[0] ? { account: account(result.rows[0]), passkey: passkeyFromJoined(result.rows[0]) } : null;
  }
  async saveAccount(value: PlayerAccount): Promise<void> { await this.pool.query(`insert into player_accounts(id,name,name_key,legacy_credential_hash,secured_at,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7)
    on conflict(id) do update set name=player_accounts.name, name_key=player_accounts.name_key, legacy_credential_hash=coalesce(player_accounts.legacy_credential_hash,excluded.legacy_credential_hash), secured_at=coalesce(player_accounts.secured_at,excluded.secured_at), updated_at=excluded.updated_at`, [value.id, value.name, playerNameKey(value.name), value.legacyCredentialHash ?? null, date(value.securedAt), date(value.createdAt), date(value.updatedAt)]); }
  async saveSession(value: PlayerDeviceSession): Promise<void> { await this.pool.query(`insert into player_device_sessions(id,account_id,token_hash,label,created_at,last_seen_at,expires_at,revoked_at) values($1,$2,$3,$4,$5,$6,$7,$8)
    on conflict(id) do update set label=excluded.label,last_seen_at=excluded.last_seen_at,expires_at=excluded.expires_at,revoked_at=excluded.revoked_at`, [value.id, value.accountId, value.tokenHash, value.label, date(value.createdAt), date(value.lastSeenAt), date(value.expiresAt), date(value.revokedAt)]); }
  async findSessionByTokenHash(hash: string, now: number): Promise<{ account: PlayerAccount; session: PlayerDeviceSession } | null> {
    const result = await this.pool.query(`update player_device_sessions s set last_seen_at=$2 from player_accounts a where s.token_hash=$1 and s.account_id=a.id and s.revoked_at is null and s.expires_at>$2 returning a.*,s.id session_id,s.account_id session_account_id,s.token_hash,s.label session_label,s.created_at session_created_at,s.last_seen_at,s.expires_at,s.revoked_at`, [hash, date(now)]);
    return result.rows[0] ? { account: account(result.rows[0]), session: sessionFromJoined(result.rows[0]) } : null;
  }
  async revokeSession(id: string, accountId: string, now: number): Promise<boolean> { const result = await this.pool.query('update player_device_sessions set revoked_at=$3 where id=$1 and account_id=$2 and revoked_at is null', [id, accountId, date(now)]); return Boolean(result.rowCount); }
  async listSessions(accountId: string, now: number): Promise<PlayerDeviceSession[]> { const result = await this.pool.query('select * from player_device_sessions where account_id=$1 and revoked_at is null and expires_at>$2 order by last_seen_at desc', [accountId, date(now)]); return result.rows.map(session); }
  async savePasskey(value: PlayerPasskey): Promise<void> { await this.pool.query(`insert into player_passkeys(id,account_id,webauthn_user_id,public_key,counter,device_type,backed_up,transports,label,created_at,last_used_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
    on conflict(id) do update set counter=excluded.counter,backed_up=excluded.backed_up,transports=excluded.transports,label=excluded.label,last_used_at=excluded.last_used_at`, [value.id, value.accountId, value.webauthnUserId, value.publicKey, value.counter, value.deviceType, value.backedUp, JSON.stringify(value.transports ?? []), value.label, date(value.createdAt), date(value.lastUsedAt)]); }
  async listPasskeys(accountId: string): Promise<PlayerPasskey[]> { const result = await this.pool.query('select * from player_passkeys where account_id=$1 order by created_at', [accountId]); return result.rows.map(passkey); }
  async updatePasskeyCounter(id: string, counter: number, usedAt: number): Promise<void> { const result = await this.pool.query('update player_passkeys set counter=$2,last_used_at=$3 where id=$1', [id, counter, date(usedAt)]); if (!result.rowCount) throw new Error('Passkey not found'); }
  async saveChallenge(value: AccountChallenge): Promise<void> { await transaction(this.pool, async (client) => { await client.query('delete from account_challenges where expires_at<=$1 or ($3::uuid is not null and kind=$2 and account_id=$3)', [date(value.createdAt), value.kind, value.accountId ?? null]); await client.query('insert into account_challenges(id,kind,challenge,account_id,created_at,expires_at) values($1,$2,$3,$4,$5,$6)', [value.id, value.kind, value.challenge, value.accountId ?? null, date(value.createdAt), date(value.expiresAt)]); }); }
  async consumeChallenge(id: string, kind: AccountChallenge['kind'], now: number): Promise<AccountChallenge | null> { const result = await this.pool.query('delete from account_challenges where id=$1 and kind=$2 and expires_at>$3 returning *', [id, kind, date(now)]); return result.rows[0] ? challenge(result.rows[0]) : null; }
  async close(): Promise<void> { await this.pool.end(); }
}

async function transaction<T>(pool: Pool, work: (client: PoolClient) => Promise<T>): Promise<T> { const client = await pool.connect(); try { await client.query('begin'); const result = await work(client); await client.query('commit'); return result; } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
const date = (milliseconds?: number): Date | null => milliseconds === undefined ? null : new Date(milliseconds);
const time = (value: unknown): number => new Date(value as string | number | Date).getTime();
const account = (row: Record<string, unknown>): PlayerAccount => ({ id: String(row.id), name: String(row.name), legacyCredentialHash: row.legacy_credential_hash ? String(row.legacy_credential_hash) : undefined, securedAt: row.secured_at ? time(row.secured_at) : undefined, createdAt: time(row.created_at), updatedAt: time(row.updated_at) });
const session = (row: Record<string, unknown>): PlayerDeviceSession => ({ id: String(row.id), accountId: String(row.account_id), tokenHash: String(row.token_hash), label: String(row.label), createdAt: time(row.created_at), lastSeenAt: time(row.last_seen_at), expiresAt: time(row.expires_at), revokedAt: row.revoked_at ? time(row.revoked_at) : undefined });
const passkey = (row: Record<string, unknown>): PlayerPasskey => ({ id: String(row.id), accountId: String(row.account_id), webauthnUserId: String(row.webauthn_user_id), publicKey: String(row.public_key), counter: Number(row.counter), deviceType: row.device_type as PlayerPasskey['deviceType'], backedUp: Boolean(row.backed_up), transports: (row.transports ?? []) as PlayerPasskey['transports'], label: String(row.label), createdAt: time(row.created_at), lastUsedAt: row.last_used_at ? time(row.last_used_at) : undefined });
const challenge = (row: Record<string, unknown>): AccountChallenge => ({ id: String(row.id), kind: row.kind as AccountChallenge['kind'], challenge: String(row.challenge), accountId: row.account_id ? String(row.account_id) : undefined, createdAt: time(row.created_at), expiresAt: time(row.expires_at) });
const sessionFromJoined = (row: Record<string, unknown>): PlayerDeviceSession => session({ id: row.session_id, account_id: row.session_account_id, token_hash: row.token_hash, label: row.session_label, created_at: row.session_created_at, last_seen_at: row.last_seen_at, expires_at: row.expires_at, revoked_at: row.revoked_at });
const passkeyFromJoined = (row: Record<string, unknown>): PlayerPasskey => passkey({ id: row.passkey_id, account_id: row.passkey_account_id, webauthn_user_id: row.webauthn_user_id, public_key: row.public_key, counter: row.counter, device_type: row.device_type, backed_up: row.backed_up, transports: row.transports, label: row.passkey_label, created_at: row.passkey_created_at, last_used_at: row.last_used_at });
